### ISSUE TITLE
Warning when loading {pilot3} package

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-utilities#11]
Hi, @bms63 .

I was wondering if you had a chance to take a look at this?

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/95468392/11f1496d-176e-4190-9181-2d46b37e916e)

I see a similar issue here, where the solution is to download Rtools https://community.rstudio.com/t/having-problems-installing-the-gt-package/23926/2 , but I did that and I still get these warnings.  Any ideas what's happening here.  Also, should this be a step to the FDA to download/install Rtools as well?

cc: @SHAESEN2 

Best,
Joel

**Comment by laxamanaj** [comment]
Update, when I try to install pilot 3 outside of the project, I do not get these warnings.

```
![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/95468392/3fb09461-e9bb-4ed2-9945-e1eaf48b0b21)

```

So there must be a version of a package in our lock file that is not meshing with our pilot3 package dependencies.  Look more into it.

**Comment by bms63** [comment]
maybe pilot1 wrappers is causing some havoc - I thought I removed it but good to check

**Comment by laxamanaj** [comment]
I think it might have something to do with the dependencies. Is there a way to compare the package dependency versions in the {pilot3} package vs the packages we have in our project renv.lock file?

pilot3 package installs before renv is implemented, but once we run renv::init(), pilot 3 installs with the warning messages.

**Comment by laxamanaj** [comment]
Linked to : https://github.com/RConsortium/submissions-pilot3-adam-to-fda/issues/25

**Comment by robertdevine** [comment]
We should be able to close #11 [here](https://github.com/RConsortium/submissions-pilot3-utilities/issues/11#issue-1859705174) along with this [issue](https://github.com/RConsortium/submissions-pilot3-adam/issues/133#issuecomment-1904917043) by end of the week. @laxamanaj, @bms63, @SHAESEN2 As noted previously renv addresses both warnings (i.e. the warnings do not appear) if renv::install( ) is used for the proprietary pilot3 package installation(s) in the Appendix steps for the updated ADRG. thx. 

The Pilot3 Utilities README will require updating as well. (Please see below since _renv_ provides the appropriate end user experience for the package installations. Alternatives include use of declarative dependencies per [box](https://cran.r-project.org/web/packages/box/index.html) or even [tidymodels](https://cran.r-project.org/web/packages/tidymodels/index.html) for ai approach or other alternatives- which may provide less complication for Pilot3 reproducibility - either way Pilot3 Team selected renv - maybe another pilot to test alternatives to _renv_ can be considered to allow for regulatory feedback if requested).

Lastly, github-flow is also an option for updating the two issues here.

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/70ad7349-b7aa-407a-a90f-1ebdad5cec9d)

'pilot1wrappers' remains included in the pilot3 renv.lock file [here](https://github.com/RConsortium/submissions-pilot3-adam/blob/main/renv.lock).

**Comment by robertdevine** [comment]
@laxamanaj , @bms63 - this issue is now moved to _In Review_ and can be closed once the [ADRG](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/28_adrg-pdf_in_readme/m5/datasets/rconsortiumpilot3/analysis/adam/datasets/adrg.pdf) is updated to include the **renv::install**( ) installation step for the pilot3 proprietary package - in place of the other three approaches tested in the series of pilots {'**pkglite**', '**install_github**' via api, and '**pak**'}. As noted above and in Issue [#133](https://github.com/RConsortium/submissions-pilot3-adam/issues/133), these two warnings are not issued during the pilot3 proprietary package installation when **renv::install**( ) is used in the ADRG _Appendix_ steps. thx.

**Comment by laxamanaj** [comment]
Closing since the solution is to first install packages from renv, then install pilot3utils. No warnings.
